AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM config for Tweeter server

#
# Global Lambda function properties. These apply to every Lambda function.
#
Globals:
  Function:
    Runtime: nodejs20.x
    CodeUri: ./dist/
    Layers:
      - !Ref tweeterLayer
    Timeout: 30
    MemorySize: 128

#
# Reusable blocks of configuration. These are referenced throughout the template to avoid duplication.
# &identifier is used to define a reusable block, and *identifier is used to reference it.
#
Metadata:
  x-common-policies: &commonPolicies
    - AWSLambdaBasicExecutionRole
    - AmazonSESFullAccess
    - CloudWatchFullAccess
    - AmazonDynamoDBFullAccess
    - AmazonS3FullAccess
    - AmazonSQSFullAccess

# Removed after implementing an api.yaml file
# x-common-cors-headers: &commonCorsHeaders
#   method.response.header.Access-Control-Allow-Origin: "'*'"

# x-common-swagger-response-headers: &commonSwaggerResponseHeaders
#   Access-Control-Allow-Origin:
#     type: string

#
# AWS resource definitions
#
Resources:
  #
  # Web API
  #

  tweeterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: tweeterApi
      Description: |
        This API provides endpoints for managing Tweeter posts and authentication. It is used in the Tweeter application backend.
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api.yaml

  #
  # Lambda Layer (reused by all Lambda functions)
  #
  tweeterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tweeterLayer
      Description: dependencies layer for Tweeter server
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: DELETE

  #
  # Web API Lambda functions
  #
  userCreateFunction: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: userCreateFunction ##### TODO: Set function name
      Handler: handlers/users/UserCreateHandler.userCreateHandler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/create ##### TODO: Set Path
            Method: POST

  userCreateFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref userCreateFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  #
  # TODO: ADD MORE WEB API LAMBDA DEFINITIONS HERE
  #

  getFolloweesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFolloweesFunction
      Handler: src/lambda/follow/GetFolloweesLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /followee/get
            Method: POST

  getFolloweesFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getFolloweesFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getFollowersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFollowersFunction
      Handler: src/lambda/follow/GetFollowersLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /follower/get
            Method: POST

  getFollowersFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getFollowersFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getFeedItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getFeedItemsFunction
      Handler: src/lambda/status/GetFeedItemsLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /feed/get
            Method: POST

  getFeedItemsFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getFeedItemsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getStoryItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getStoryItemsFunction
      Handler: src/lambda/status/GetStoryItemsLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /story/get
            Method: POST

  getStoryItemsFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getStoryItemsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  postStatusItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: postStatusItemFunction
      Handler: src/lambda/status/PostStatusItemLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /status/post
            Method: POST

  postStatusItemFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref postStatusItemFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUserFunction
      Handler: src/lambda/user/GetUserLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/get
            Method: POST

  getUserFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getUserFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  loginFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: loginFunction
      Handler: src/lambda/authentication/LoginLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/login
            Method: POST

  loginFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref loginFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  registerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: registerFunction
      Handler: src/lambda/authentication/RegisterLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/register
            Method: POST

  registerFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref registerFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  logoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: logoutFunction
      Handler: src/lambda/authentication/LogoutLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/logout
            Method: POST

  logoutFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref logoutFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getIsFollowStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getIsFollowStatusFunction
      Handler: src/lambda/user/GetIsFollowerStatusLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/isfollower
            Method: POST

  getIsFollowStatusFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getIsFollowStatusFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getNumFollowees:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNumFollowees
      Handler: src/lambda/user/GetFolloweeCountLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/numfollowees
            Method: POST

  getNumFolloweesApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getNumFollowees
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  getNumFollowers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNumFollowers
      Handler: src/lambda/user/GetFollowerCountLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/numfollowers
            Method: POST

  getNumFollowersApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref getNumFollowers
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  follow:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: follow
      Handler: src/lambda/user/FollowLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/follow
            Method: POST

  followApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref follow
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  unfollow:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: unfollow
      Handler: src/lambda/user/UnfollowLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId: !Ref tweeterApi
            Path: /user/unfollow
            Method: POST

  unfollowApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref unfollow
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${tweeterApi}/*/*/*"

  #
  # SQS Queue Lambda Functions  (This will become relevant in Milestone 4. For M3, leave this section commented out.)
  #

  #   MyQueueFunction:
  #     Type: AWS::Serverless::Function
  #     Properties:
  #       FunctionName: MyQueueFunction
  #       Handler: <PATH TO LAMBDA HANDLER>
  #       Policies: *commonPolicies
  #       Events:
  #         SQSTrigger:
  #           Type: SQS
  #           Properties:
  #             Queue: !GetAtt MyQueue.Arn
  #             Enabled: true

  #
  # DynamoDB Tables
  #
  followTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: follow
      AttributeDefinitions:
        - AttributeName: followId
          AttributeType: S
        - AttributeName: followerUserId
          AttributeType: S
        - AttributeName: followeeUserId
          AttributeType: S
        - AttributeName: followTime
          AttributeType: N
      KeySchema:
        - AttributeName: followId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: follower_index
          KeySchema:
            - AttributeName: followerUserId
              KeyType: HASH
            - AttributeName: followTime
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          Projection:
            ProjectionType: ALL
        - IndexName: followee_index
          KeySchema:
            - AttributeName: followeeUserId
              KeyType: HASH
            - AttributeName: followTime
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          Projection:
            ProjectionType: ALL

  userTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: alias
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: alias_index
          KeySchema:
            - AttributeName: alias
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          Projection:
            ProjectionType: ALL

  statusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: status
      AttributeDefinitions:
        - AttributeName: statusId
          AttributeType: S
        - AttributeName: postTime
          AttributeType: N
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: statusId
          KeyType: HASH
        - AttributeName: postTime
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: user_index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: postTime
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          Projection:
            ProjectionType: ALL

  sessionTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: sessionTokens
      BillingMode: PROVISIONED
      AttributeDefinitions:
        - AttributeName: tokenId
          AttributeType: S
      KeySchema:
        - AttributeName: tokenId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expirationTime
      Tags:
        - Key: Environment
          Value: Production

  cachedFeedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cachedFeed
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: postTime
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: postTime
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: Purpose
          Value: FeedCache

  #
  # S3 Buckets
  #

  ProfileImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tweeter-profile-images-kevkp
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 3000
